Erro léxico na linha 5, coluna 13: token recognition error at: '@'. Caractere 'desconhecido' na posição 13.
Traceback (most recent call last):
  File "/home/linuxbrew/.linuxbrew/lib/python3.13/site-packages/antlr4/Lexer.py", line 137, in nextToken
    ttype = self._interp.match(self._input, self._mode)
  File "/home/linuxbrew/.linuxbrew/lib/python3.13/site-packages/antlr4/atn/LexerATNSimulator.py", line 104, in match
    return self.execATN(input, dfa.s0)
           ~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/home/linuxbrew/.linuxbrew/lib/python3.13/site-packages/antlr4/atn/LexerATNSimulator.py", line 195, in execATN
    return self.failOrAccept(self.prevAccept, input, s.configs, t)
           ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/linuxbrew/.linuxbrew/lib/python3.13/site-packages/antlr4/atn/LexerATNSimulator.py", line 254, in failOrAccept
    raise LexerNoViableAltException(self.recog, input, self.startIndex, reach)
antlr4.error.Errors.LexerNoViableAltException: LexerNoViableAltException('@')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/arthur/Desktop/College/Compiladores/Compiladores/compiladores-t6/color-art/colorart.py", line 66, in main
    arvore = parser.programa()
  File "/home/arthur/Desktop/College/Compiladores/Compiladores/compiladores-t6/color-art/ColorArtParser.py", line 227, in programa
    self.declaration()
    ~~~~~~~~~~~~~~~~^^
  File "/home/arthur/Desktop/College/Compiladores/Compiladores/compiladores-t6/color-art/ColorArtParser.py", line 299, in declaration
    self.color()
    ~~~~~~~~~~^^
  File "/home/arthur/Desktop/College/Compiladores/Compiladores/compiladores-t6/color-art/ColorArtParser.py", line 449, in color
    self.match(ColorArtParser.ID)
    ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
  File "/home/linuxbrew/.linuxbrew/lib/python3.13/site-packages/antlr4/Parser.py", line 124, in match
    self.consume()
    ~~~~~~~~~~~~^^
  File "/home/linuxbrew/.linuxbrew/lib/python3.13/site-packages/antlr4/Parser.py", line 348, in consume
    self.getInputStream().consume()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/home/linuxbrew/.linuxbrew/lib/python3.13/site-packages/antlr4/BufferedTokenStream.py", line 100, in consume
    if self.sync(self.index + 1):
       ~~~~~~~~~^^^^^^^^^^^^^^^^
  File "/home/linuxbrew/.linuxbrew/lib/python3.13/site-packages/antlr4/BufferedTokenStream.py", line 112, in sync
    fetched = self.fetch(n)
  File "/home/linuxbrew/.linuxbrew/lib/python3.13/site-packages/antlr4/BufferedTokenStream.py", line 124, in fetch
    t = self.tokenSource.nextToken()
  File "/home/linuxbrew/.linuxbrew/lib/python3.13/site-packages/antlr4/Lexer.py", line 139, in nextToken
    self.notifyListeners(e)		# report error
    ~~~~~~~~~~~~~~~~~~~~^^^
  File "/home/linuxbrew/.linuxbrew/lib/python3.13/site-packages/antlr4/Lexer.py", line 294, in notifyListeners
    listener.syntaxError(self, None, self._tokenStartLine, self._tokenStartColumn, msg, e)
    ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/linuxbrew/.linuxbrew/lib/python3.13/site-packages/antlr4/error/ErrorListener.py", line 60, in syntaxError
    delegate.syntaxError(recognizer, offendingSymbol, line, column, msg, e)
    ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/arthur/Desktop/College/Compiladores/Compiladores/compiladores-t6/color-art/colorart.py", line 36, in syntaxError
    raise ValueError(error_message)
ValueError: Erro léxico na linha 5, coluna 13: token recognition error at: '@'. Caractere 'desconhecido' na posição 13.

